### ISSUE TITLE
取引分析機能を実装したい

### ISSUE THREAD

**Issue by Eigo-Mt-Fuji** [Eigo-Mt-Fuji/fx-report#8]
## やりたいこと

- 取引の実績が蓄積されてきたので分析用の機能を作りたい
    - なぜ必要なのか、利用イメージを簡単に整理する
    - まず、取得できる取引の情報と分析したい属性、分析軸を検討
    - 次に、実装方法を考える

- https://github.com/Eigo-Mt-Fuji/efg-confidential/issues/22 の一貫
    - https://github.com/Eigo-Mt-Fuji/efg-confidential/issues/27
    - https://github.com/Eigo-Mt-Fuji/efg-confidential/issues/28
    - https://github.com/Eigo-Mt-Fuji/efg-confidential/issues/25

- https://github.com/Eigo-Mt-Fuji/fx-report/issues/9 の続き
    - next.js, NestJs, 整理したモデリング方法を踏まえて、設計していく

## やりたいこと(つづき)

- 取引を今後も継続させたい。
- そのため、自前の分析機能を実装し、分析結果に表示されたグラフを活用して、今後の取引のアプローチを改善していきたい
    - エントリーのタイミングや投入するロットの決定など、精度をアップしていきたい
      - たとえば
        - ○曜の何時〜何時を重点的に狙って取引する。
        - ○曜は取引を控える。静観する

- なぜ自前で実装するのか?   
  - 自由な実装手段を確立しておくことがねらい
      - 自由な実装手段とは?
          - チャートを使った可視化を、ExcelやTablauなど特定のソリューションに限らず、自分で自由自在に実装できる状態を作ること
      - なぜ必要なのか?
          - ExcelやRedash, Tablauなど可視化に適した既存の製品があるけど、企業内部の分析用途が中心。
              - 一般公開するサービスや自前の管理機能には搭載しにくい
              - これは個人の志(こころざし)の問題だけど、Tablau頼みとかだと、ライセンス料の分、収入機会が減ってる気がする
                 - Tablau 3Creator 年間\302,400, Looker 3人で年間1,000,000円
                 - しかも、特定の製品に頼ってしまうと、能力や人材価値がプロダクトの範囲に制限されそう
                     - エンジニアリングの観点ではSQLが使える、といったことしかアピールできない
                         - https://www.bigdata-navi.com/lp/pattern1_2/?utm_source=google&utm_medium=cpc&utm_campaign=other&gclid=CjwKCAjw0a-SBhBkEiwApljU0h90LH_2QaEa-qyyB6F7ZweODIHbXM14bmZVFFrilaUiwbgl0m32YhoCK-IQAvD_BwE
  - 今後について できれば、新規開発、特にマルチメディアを活用したアプリケーション開発に強いソフトウェアエンジニアを目指したい
    - https://github.com/Eigo-Mt-Fuji/efg-confidential/issues/11
  
## 利用イメージ

- 既存のfx-reportページに「分析ページへ」ボタンを１つ配置
- 「分析ページへ」ボタンを押下すると、分析ページに遷移(分析結果が表示される)
- 補足
    - ページを開くとそこに分析結果が表示されればOK
        - このページ?
            - https://www.efgriver.com/fx-reports/
                - ここに表示すると、長すぎてわからない
                    - タブで切り替える仕組みにする
                        - やり方がわからない。現状タブで切り替えられる仕組みになってない
                            - 分析ページを別に用意して、年間実績の下あたりに導線(ボタン)を置く
                                - ボタンを押下すると、分析ページに遷移して、分析結果が出るイメージ

## TODO

- [x] 機能仕様をまとめる https://github.com/Eigo-Mt-Fuji/fx-report/wiki/fx-report%E6%A9%9F%E8%83%BD%E4%BB%95%E6%A7%98
- [x] アーキテクチャ https://app.diagrams.net/?libs=aws4&splash=0#G1n4ex3hBDjp6sJXwIJKcD70wUk6HTqqtg
- [x] UI仕様設計
- [x] UI実現性調査
- [x] プログラム開発タスク細分化
- [x] 一部調査
- [x] データフロー(いるのか..?)
- [x] プログラム実装・動作確認
- [x] リリース
- [x] ボーナス: こだわりポイント・アウトプット機会の考えを膨らませる
  - 設計時のモデリング方法にこだわってみる
    - https://github.com/Eigo-Mt-Fuji/efg-confidential/issues/25
  - 画像形式にこだわってみる
    - https://ipeinc.jp/blog/avif/
    - https://ics.media/entry/201001/
  - CodeQLを使って静的解析をやってみる
    - https://codeql.github.com/docs/writing-codeql-queries/about-codeql-queries/
  - アルゴリズム・データ構造・計算機科学を意識して導入
    - 計算幾何学が解決する問題 - http://www.ne.jp/asahi/music/marinkyo/kvalito/geometrio.html.ja
        - グラフ理論 - https://qiita.com/maskot1977/items/b55c6d1c85bcf0ec0d08
        - 地理的・幾何学的最適化問題
            - 巡回セールスマン問題 - 辺の長さ合計を最小にする巡回閉路を探す
            - 最小木問題 - 辺の長さ合計を最小にする木を探す
            - 郵便局問題 = 最近点問題 = ある地点に最も近い点（郵便局）を答える問題
                - すべての点との距離を求めれば，最近点を求めることはできる
                    - 大量の点が対象になる場合に、計算時間・計算量が肥大化しないように工夫したい。少数の点だけを見て求めることは可能か?
                        - 探索の対象を限定すること
                            - 1次元 - データがソートされていれば，データ数nに対して，log n時間で探索可能
                            - ２次元での探索 - ２分探索の構造を実現できる? 小領域ごとに細分化できれば実現できそう
  - 人気のアニメーションライブラリを導入
    - GSAPは欧米では一番使われているライブラリ(らしい)
        - Google Trend 
        - https://trends.google.co.jp/trends/explore?date=all&q=GSAP,Typed.js,ScrollReveal,TweenJs
        - Showcase
        - https://greensock.com/showcase/
        - 参考
        - https://maps.google.com/localguides/
    - それ以外に使ってみたいもの
        - ScrollReveal react
            - https://qiita.com/uwattotaitai/items/5957eda0c63634fbaa56

        - Typed.js react
            - https://jsfiddle.net/mattboldt/60h9an7y/
  - 組み合わせて創発
    - 自分に近いトピックを組合せる
        - 便利ツール
        - プログラミング
        - クラウドインフラ
        - 数学
        - ソフトウェア設計
        - トレンド
        - 気になる作品
    - 何を創発する?
        - 自分が好きなもの、気になったものにまつわるなにか

## TODO(プログラム実装・動作確認)

プログラム実装・動作確認タスクを細分化する。

- [x] react-adminパッケージのコンポーネントを組み合わせてfx-report用のDOM要素ツリーの構成を練る
    - react-adminパッケージのコンポーネントとは?
       - Admin
       - Resource
         - 参照系
             - show 
             - list
       - DataProvider

- [x] DOM要素を構成するコンポーネントをリストにする

- [x] DOM要素を構成するコンポーネントごとのTODOを整理する
    - ファイル名
    - コンポーネント名
    - 配置
    - スタイル
    - 子コンポーネント
    - 依存react-hooks
    - 依存関係パッケージ
    - 処理シーケンス
    - 実装課題
    - 調査事項

- [x] DataProviderに設定するrest apiのI/Fを決める
     - host
     - path
     - http method 
     - query 
- [x] 分析用のページ雛型をつくる
- [x] 分析用のページ実装
- [x] 分析用の各コンポーネント実装
- [x] 分析バックエンドapi nestjsプロジェクト作成
    - nest.jsの使い方を調べる
        - 何を調べる?
            - プロジェクト作成方法
            - MVC部品作成方法
                - nest g controller fx-transaction

- [x] DataProviderに設定するrest apiのI/Fに合わせてnestjsで api実装

- [x] nestjs サーバレスデプロイ用の設定
   - Serverless framework
      - どんな設定か調査
- [x] next.js サーバレスデプロイ用の設定
   - Serverless framework
      - どんな設定か調査
   - URL
      - https://welcome.efgriver.com/admin/
- [x] デプロイ・動作確認 

- [x]  実装を振り返って、TODOタスクの改善点と次の実装課題をissueにまとめる

## 参考

- 政策金利会合などのスケジュール https://info.monex.co.jp/us-stock/basic-guide/knowledge/schedule2022.html
- FXのトレード記録で自分のトレードを分析！記録内容や分析方法を解説 - https://real-int.jp/articles/276/
- FX「トレード日記」はどうつける  - https://frantic.jp/basic/2299/

**Comment by Eigo-Mt-Fuji** [comment]
- 次は、参考にしたサイトでの紹介内容と照らし合わせて、過不足や改善点があるか検討してみる
    - 要件の考慮漏れや、解釈のブレがあれば訂正

**Comment by Eigo-Mt-Fuji** [comment]
- 実装については、nextjsへのリプレースが済んでから進行
  - https://github.com/Eigo-Mt-Fuji/fx-report/issues/9

**Comment by Eigo-Mt-Fuji** [comment]
アローダイアグラムのクリティカルパスを書くなら
stateDiagramよりflowchartがよい
なぜなら後者だと、→にラベルを付与できて日数などを書けるメリットがある

**Comment by Eigo-Mt-Fuji** [comment]
うそ。
stateDiagramで `機能設計 --> 論理DB設計: 1日` のように書くことで
工数感をラベルで表現できる

**Comment by Eigo-Mt-Fuji** [comment]
UI設計とAPI外部仕様設計ってそんなに関係ある?

**Comment by Eigo-Mt-Fuji** [comment]
UI設計のレビューの前にはすくなくとも論理
https://xtech.nikkei.com/atcl/nxt/column/18/01195/063000012/?P=2

**Comment by Eigo-Mt-Fuji** [comment]
設計でやるべきことを別なissueにまとめました

https://github.com/Eigo-Mt-Fuji/efg-confidential/issues/25

```
目次
背景
設計フェーズの進め方想定
設計フェーズ別モデリング方法
具体例#flowchart
具体例#classDiagram
具体例#sequenceDiagram
具体例#erDiagram
具体例#stateDiagram
具体例#gantt
具体例#journey
具体例#requirementDiagram
考察
まとめると
```

**Comment by Eigo-Mt-Fuji** [comment]
Going to Productionは持ち越し

---

- In General
    - Use caching wherever possible.
    - Ensure your database and backend are deployed in the same region.
    - Aim to ship the least amount of JavaScript possible.
    - Defer loading heavy JavaScript bundles until needed.
    - Ensure logging is set up.
    - Ensure error handling is set up.
    - Configure the 404 (Not Found) and 500 (Error) pages.
    - Ensure you are measuring performance.
    - Run Lighthouse to check for performance, best practices, accessibility, and SEO. For best results, use a production build of Next.js and use incognito in your browser so results aren't affected by extensions.
    - Review Supported Browsers and Features.
- Performance
    - next/image and Automatic Image Optimization
    - Automatic Font Optimization
    - Script Optimization
    - Improve loading performance

**Comment by Eigo-Mt-Fuji** [comment]
https://app.diagrams.net/?libs=aws4&splash=0

**Comment by Eigo-Mt-Fuji** [comment]
画像形式にこだわってみる
https://ipeinc.jp/blog/avif/
https://ics.media/entry/201001/

**Comment by Eigo-Mt-Fuji** [comment]
UIについてイメージを整理した
https://github.com/Eigo-Mt-Fuji/fx-report/wiki/fx-report%E6%A9%9F%E8%83%BD%E4%BB%95%E6%A7%98#%E5%88%86%E6%9E%90%E6%A9%9F%E8%83%BDui

**Comment by Eigo-Mt-Fuji** [comment]
UIについて(つづき)

react adminを使うことにしたい
https://github.com/marmelab/react-admin

- v3.9.0以降 Typescriptサポートしている
  - https://github.com/marmelab/react-admin
    - issues/4505#issuecomment-697666524
      - TypeScript types - this task is done 🥳 . Starting with 3.9.0
 
- 日本語化プラグインを発見
  - https://github.com/bicstone/ra-language-japanese

- カスタマイズ(自分で実装したグラフを差し込むこと)はできるのか?
  - 要調査

- next.jsで動くのか?

- next-auth.jsと共存できるのか?

**Comment by Eigo-Mt-Fuji** [comment]
react-adminを使う前提で
- nestjs api実装
- nextjs spa実装
をやっていく

**Comment by Eigo-Mt-Fuji** [comment]
タスクを細分化する。

- 分析用のページ雛型をつくる

- react-adminパッケージのコンポーネントを組み合わせてfx-report用のDOM要素ツリーの構成を練る
    - react-adminパッケージのコンポーネントとは?
       - Admin
       - Resource
       - DataProvider

- DOM要素を構成するコンポーネントをリストにする

- DOM要素を構成するコンポーネントごとのTODOを整理する
    - ファイル名
    - コンポーネント名
    - 配置
    - スタイル
    - 子コンポーネント
    - 依存react-hooks
    - 依存関係パッケージ
    - 処理シーケンス
    - 実装課題
    - 調査事項

- DataProviderに設定するrest apiのI/Fを決める
     - host
     - path
     - http method 
     - query 
    
- 分析バックエンドapi nestjsプロジェクト作成

- nest.jsの使い方を調べる
    - 何を調べる?
        - MVC部品作成方法
            - nest g controller fx-transaction

- DataProviderに設定するrest apiのI/Fに合わせてapi実装

**Comment by Eigo-Mt-Fuji** [comment]
![architecture-fx-report-analysis-react-admin学ぶ drawio](https://user-images.githubusercontent.com/14959592/161935782-a69995e7-db82-4c70-820c-5d4aebe043cb.png)

**Comment by Eigo-Mt-Fuji** [comment]
https://marmelab.com/react-admin/Admin.html#dashboard

**Comment by Eigo-Mt-Fuji** [comment]
とりあえず実装のための構造の理解が進んだ。

分析用の各コンポーネント実装 https://github.com/Eigo-Mt-Fuji/fx-report/tree/master/src/components/admin
  - admin
    - dashboard.tsx
    - fx-analysis-week-hour-chart.tsx
    - fx-analysis-week-hour-table.tsx
    - fx-analysis-list.tsx

↓
- DataProviderに設定するrest apiのI/Fに合わせてnestjsで api実装
    - https://github.com/Eigo-Mt-Fuji/nestjs-subject/blob/main/src/fx-analysis/fx-analysis.controller.ts

↓

nestjs サーバレスデプロイ用の設定

↓

next.js サーバレスデプロイ用の設定

↓

デプロイ・動作確認

↓

実装を振り返って、TODOタスクの改善点と次の実装課題をissueにまとめる

**Comment by Eigo-Mt-Fuji** [comment]
.babelrcファイルが存在すると、SWCが使われないらしい

Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" 
https://app.netlify.com/sites/goofy-bohr-20d740/deploys/624d7ec71e43d90009293ced#L186

**Comment by Eigo-Mt-Fuji** [comment]
- 今日の進捗

- react-adminのカスタムlayoutを導入しディレクトリ構成を見直した
    - https://github.com/Eigo-Mt-Fuji/fx-report/pull/30
    - 
- TerraformでS3バケットを作成して、Github workflow経由で取引明細CSVファイルをS3に連携した
    - https://github.com/Eigo-Mt-Fuji/fx-report/pull/31/files

```
fujikawaeigo-no-MacBook-Pro:fx-report e_fujikawa$ aws s3 ls s3://fx-report-data.prd.efgriver.com/src/data/fx_transactions/
2022-04-07 19:49:29      12289 kessai202101.csv
2022-04-07 19:49:29      86606 kessai202102.csv
2022-04-07 19:49:29     232529 kessai202103.csv
2022-04-07 19:49:29      20348 kessai202104.csv
2022-04-07 19:49:29       1392 kessai202105.csv
2022-04-07 19:49:29       5883 kessai202106.csv
2022-04-07 19:49:29       5647 kessai202107.csv
2022-04-07 19:49:29       5878 kessai202108.csv
2022-04-07 19:49:30      20828 kessai202109.csv
2022-04-07 19:49:30      52172 kessai202110.csv
2022-04-07 19:49:29       8553 kessai202111.csv
2022-04-07 19:49:30       1008 kessai202112.csv
2022-04-07 19:49:29       4798 kessai202201.csv
2022-04-07 19:49:29       4961 kessai202202.csv
2022-04-07 19:49:30       8892 kessai202203.csv
```

**Comment by Eigo-Mt-Fuji** [comment]
- 情報収集 1h
- タスク整理1h
- 設計1h
- 開発2h
- レビュー・検討2h
- ミーティング 0.5h
- 今日の進捗、タスク整理0.5h

**Comment by Eigo-Mt-Fuji** [comment]
- テーブルとグラフそれぞれ調査する
              - テーブル https://mui.com/components/tables/#virtualized-table
                - できそう。
                  - cellRenderer というプロパティでテーブルのセル毎の値に応じて独自のレンダリングが行える様子(なので、週・時間毎の損益額似合わせてテーブルセルの塗りつぶし色を５段階で変えることができそう)
              - グラフ https://recharts.org/en-US/examples/HighlightAndZoomLineChart
                - できそう rechartのLineChartコンポーネントを使って折れ線グラフを作り、Lineコンポーネントで実際に線を引く。前提として、時間帯ごとにソートした配列を事前に準備する。配列の各要素にその時間帯の各曜日の損益額の属性を持たせておく事が必要。その上でLineChartコンポーネントで曜日ごとの折れ線グラフを表示するには、LineChartコンポーネント内にLineコンポーネントを複数作成することがポイント。LineコンポーネントのdataKey属性に曜日に対応する属性名を指定することで、曜日ごとに線を描くことができる。

**Comment by Eigo-Mt-Fuji** [comment]
- serverless frameworkを使ってnext.jsのアプリケーションをawsにデプロイする方法を調査する
   - 完成形がなかなか見つからなかったので組み上げた

```
# https://www.serverless.com/framework/docs/getting-started
service: fx-report
variablesResolutionMode: 20210326
configValidationMode: error
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  lambdaHashingVersion: 20201221
  memorySize: 512
  timeout: 15
  stackName: ${sls:stage}-fx-report
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:*"
          Resource:
            - 'arn:aws:s3:::${emv:NEXT_PUBLIC_DATA_S3_BUCKET}'
            - 'arn:aws:s3:::${emv:NEXT_PUBLIC_DATA_S3_BUCKET}/*'
# whatis serverless framework component: https://github.com/serverless/components
fxReportApp:
  # whatis @sls-next/serverless-component: https://github.com/serverless-nextjs/serverless-next.js
  component: "@sls-next/serverless-component@3.7.0"
  inputs:
    policy: "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole	"
    # TODO: fix domain https://github.com/serverless-nextjs/serverless-next.js#custom-domain-name
    domain: ["welcome", "efgriver.com"] # [ sub-domain, domain ]
    domainMinimumProtocolVersion: "TLSv1.2_2021"
    certificateArn: "arn:aws:acm:us-east-1:047980477351:certificate/91defbde-5ced-4c62-b817-c4390fa4cbf7"
    # TODO: fix nodejs runtime https://github.com/serverless-nextjs/serverless-next.js#lambda-at-edge-configuration
    runtime: "nodejs14.x"

    # TODO: fix memory https://github.com/serverless-nextjs/serverless-next.js#lambda-at-edge-configuration
    memory:
      defaultLambda: 1024
      apiLambda: 2048
      imageLambda: 2048
    # TODO: fix timeout setting https://github.com/serverless-nextjs/serverless-next.js#lambda-at-edge-configuration
    #  FYI https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html
    timeout:
      defaultLambda: 20
      apiLambda: 15
      imageLambda: 15
    # https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/userguide/transfer-acceleration.html
    # Transfer Acceleration で使用するバケットは、ピリオド (".") が含まれていない DNS 準拠の名前にする必要があります
    enableS3Acceleration: false
```

**Comment by Eigo-Mt-Fuji** [comment]
TODO(プログラム実装・動作確認)
タスクを細分化する。パート２
----
実際やってみた履歴、やってみて違った部分・不足していた部分も踏まえて整理し直した

- リポジトリ作成・開発準備
  - 雛形を作成/パッケージ導入 - react-adminの説明を見ながらとりあえず作成
    - https://github.com/Eigo-Mt-Fuji/fx-report/pull/23
    - https://github.com/Eigo-Mt-Fuji/fx-report/pull/24
    - https://github.com/Eigo-Mt-Fuji/fx-report/pull/26
    - https://github.com/Eigo-Mt-Fuji/fx-report/pull/27
  - 知らないことを調査して理解する
    - next.jsのpagesディレクトリ・ファイル構成から、URLのルーティングルールがどう決まるのか
    - react-adminのAdminコンポーネントとResourceコンポーネントの役割と使い方
    - ra-data-json-serverとは?
    - そもそもjsonServerとは?
    - jsonplaceholder.typicode.comとは?
    - nest.jsでCORSに対応するには?
      - CORSとは?
        - OPTIONSリクエストは飛ばないことがある?
  - 雛形を見直す - react-adminカスタムレイアウト導入
    - https://github.com/Eigo-Mt-Fuji/fx-report/pull/30
  - 雛形を見直す - ディレクトリ名をadmin->fx-analysisにリネーム
    - https://github.com/Eigo-Mt-Fuji/fx-report/pull/28
  - nest.jsの使い方をおさらいする
    - https://github.com/Eigo-Mt-Fuji/efg-confidential/issues/28
  - nest.js側にダミーコントローラを作成する
    - https://github.com/Eigo-Mt-Fuji/fx-report-api/commit/ffb337eacb3a89f03694375100dac217dcbba24c
  - nest.jsとnext.jsの２つのアプリの疎通を確認する
    - https://github.com/Eigo-Mt-Fuji/fx-report-api/commit/f38768f8df446b3598349276509a84aafd0fdf80
  - nestjs-subject gitリポジトリリネーム
    - fx-reportに合わせる形でnestjs-subject -> fx-report-api
  - そもそもnest.js apiを分けた場合に、どうデータを共有すべきか考えてないことに気づく
    - TerraformでS3バケットを作成して、Github workflow経由で取引明細CSVファイルをS3に連携できるか試す
      - https://github.com/Eigo-Mt-Fuji/fx-report/pull/31/files
  - nest.js/next.jsを一般公開することが本当にできるのか不安になる
      - https://github.com/Eigo-Mt-Fuji/fx-report/issues/8#issuecomment-1092403278
  - wikiに参考サイトのリファレンスをまとめておく
    - https://github.com/Eigo-Mt-Fuji/fx-report/wiki#reference

- プログラム実装・動作確認
  - 取引明細データをfx-report-apiリポジトリ側の実装から参照できるようにS3にデータを複製する
  - 分析機能ダッシュボードを実装する
    - グラフを表示する
      - データを取得する
      - 実装
        - rechartのLineChartコンポーネントを使ってグラフ形式で損益を表示する
    - テーブルを表示する
      - データを取得する
      - 実装
        - muiのTableコンポーネントを使って表形式で損益を表示する
    - データを取得するREST APIを実装する
      - nest.jsからAWS S3を参照する方法を検証する
      - 処理シーケンスを整理する
      - Nestモジュール構成を設計する
      - Nestモジュールを作成
      - コーディング
      - 単体動作確認
    - デプロイ
      - デプロイ方法を調査する https://github.com/Eigo-Mt-Fuji/fx-report/issues/8#issuecomment-1092403278
          - AWSデプロイ
          - 結合動作確認
    - テスト
        - next.js, nest.jsのテスト方法を理解する
        - unitテストの作り方をおさらいする
        - 各種テストのおさらいをしておく
            - 機能テスト観点を整理する
            - パフォーマンステスト
            - ペネトレーションテスト - https://aws.amazon.com/jp/security/penetration-testing/
        - 過去のテスト時のやりとりをふりかえる

**Comment by Eigo-Mt-Fuji** [comment]
テストについて。予め以下の点を整理してから望むこと。

- next.js, nest.jsのテスト方法を理解する
- unitテストの作り方をおさらいする
- 各種テストのおさらいをしておく
    - 機能テスト観点を整理する
    - パフォーマンステスト
    - ペネトレーションテスト - https://aws.amazon.com/jp/security/penetration-testing/
- 過去のテスト時のやりとりをふりかえる

**Comment by Eigo-Mt-Fuji** [comment]
- テーブルとグラフそれぞれのプロトタイプコンポーネントを実装した
  - https://github.com/Eigo-Mt-Fuji/fx-report/pull/38

- その経過で emotion と muiについて理解度がアップしたのでwikiにまとめた
  - https://github.com/Eigo-Mt-Fuji/fx-report/wiki/Memo-material-ui(mui)%E3%81%A8emotion
    - muiの説明わかりにくいし、emotion複雑..
       - たかがcssのclass定義するためにめちゃくちゃ時間かかった

**Comment by Eigo-Mt-Fuji** [comment]
![Screenshot_20220417-125236_Chrome](https://user-images.githubusercontent.com/14959592/163699625-69af57f7-ef7c-457b-adfe-ec4bb7a13ff9.jpg)

Next.js デプロイ疎通済み

**Comment by Eigo-Mt-Fuji** [comment]
- 2021年

1/30 FX取引実績を表示するアプリをgatsbyで実装する企画 https://github.com/Eigo-Mt-Fuji/portfolio-2021/commit/de608bae1b03b0f7048377f74fe1ccf6f6ad29c4

2/1 年間実績のグラフ表示対応、日次実績の表示を調整、変動幅(pips)をBarChart->LineChartに修正 https://github.com/Eigo-Mt-Fuji/portfolio-2021/commit/9e735b2f6e877eb7e7a544fa4a1ded6aae77f9f0

2/13 CORSエラー修正(リファラポリシーをno-referrer->strict-origin-when-cross-originに修正) https://github.com/Eigo-Mt-Fuji/portfolio-2021/commit/e2d196c16f24d761ba2f3c2e1e9a34a4125fae87

2/20 2月3周目の取引実績とイベント、反省を記載 https://github.com/Eigo-Mt-Fuji/portfolio-2021/commit/e9f3617e661413c544be6a057b183e377ad74d8f

2/28 月次実績のグラフのY軸に利益/pipsのラベル表示、月次実績グラフのデフォルト表示を週足にする+週足・日足切り替え対応,  https://github.com/Eigo-Mt-Fuji/portfolio-2021/commit/d0cc1fe2e3ef4bc693c971ca2ac0dec701a48fa5

- 2022年

3/26 新規建玉注文１回について決済注文を複数回できるようにする

3/27 SBI証券の取引明細ダウンロード後の加工およびリポジトリに所定の場所に反映する作業をGithub actionで自動で行われるようにする

3/27 月次実績のpips表示は絶対値を採用(本来の期待値を把握できるように、プラスマイナスの打ち消し回避のため絶対値に直した上で、絶対値の合算値を表示)

4/1 gatsby -> next.js切替, react-adminダッシュボード / emotion導入

4/1 netlifyデプロイステータスバッジを導入
